{{- $replicas := int .Values.hermitcrab.replicas }}
{{- if and .Values.hermitcrab.pdb.enabled (gt $replicas 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hermitcrab.name" . }}
  namespace: {{ include "hermitcrab.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "hermitcrab.selectorLabels" . | nindent 4 }}
spec:
  {{- if .Values.hermitcrab.pdb.minAvailable }}
  minAvailable: {{ .Values.hermitcrab.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.hermitcrab.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.hermitcrab.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hermitcrab.selectorLabels" . | nindent 6 }}
{{- end }}
