{{- $replicas := int .Values.openTfMirror.replicas }}
{{- if and .Values.openTfMirror.pdb.enabled (gt $replicas 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "open-tf-mirror.name" . }}
  namespace: {{ include "open-tf-mirror.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "open-tf-mirror.selectorLabels" . | nindent 4 }}
spec:
  {{- if .Values.openTfMirror.pdb.minAvailable }}
  minAvailable: {{ .Values.openTfMirror.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.openTfMirror.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.openTfMirror.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open-tf-mirror.selectorLabels" . | nindent 6 }}
{{- end }}
